libegl: Add RPROVIDES for libegl.so
libegl-dev provides libegl.so but this is not found when do_rootfs installs dependent packages
for certain package configurations. Add RPROVIDES so it is found.

Fixes do_rootfs build errors of the form:
error: Can't install gles-user-module-1.0-r0@koelsch: no package provides libEGL.so